#!/bin/bash
srcinfile="$1"
srcoutfile="$2"
dstdir="$3"
cmndir="$4"

if [ -z "$1" ] || [ -z "$2" ] || [ -z "$3" ] || [ -z "$4" ]; then
	echo "Usage: $0 <source file> <destination file> <destination dir> <common dir>"
else
	echo resolving xmlincs of $srcinfile to $srcoutfile with destination dir: $dstdir, common dir: $cmndir
	python "$(dirname "$0")"/src/xmlinc.py -i $srcinfile -o $srcoutfile -d $dstdir -c $cmndir
fi
